defaults:
  - model: HAN
general:
  N_EPOCHS: 1
  batch_size: 256
  vocab_size: 32000
  word_hidden_dim: 32
  sent_hidden_dim: 32
  padding_idx: 1
  embed_dim: 200
  min_freq: 5
  num_class: 2
  gpus: '6'
early_stop:
  min_delta: 0.005
  patience: 3
