defaults:
  - model: HAN
common:
  N_EPOCHS: 1
  batch_size: 64
  vocab_size: 32000
  word_hidden_dim: 32
  sent_hidden_dim: 32
  padding_id: 1
  embed_dim: 200
  min_freq: 5
  num_class: 2
  gpus: '6'