name: hf_bigbird

args:
  _target_: src.model.BigBird.BigBird.Bigbird
  pretrained_model_name_or_path: nlp-waseda/bigbird-base-japanese

data_module:
  _target_: src.datamodule.HFModelDataModule.CreateHFModelDataModule
  batch_size: 4
