name: HAN

model:
  _target_: src.model.HAN.HierAttnNet
  vocab_size: 32000
  weight_drop: 0.0
  locked_drop: 0.0
  embed_drop: 0.0
  last_drop: 0.0
  word_hidden_dim: 50
  sent_hidden_dim: 50
  padding_idx: 1
  num_class: 2

data_module:
  _target_: src.datamodule.HANDataModule.CreateHANDataModule
  batch_size: 64

tokenizer:
  _target_: src.tokenizer.tokenizer_HAN.HANtokenizer
  sent_length: 256
  doc_length: 256
  vocab_size: 32000
  min_freq: 1
  embed_dim: 200
  tokenizer_type: 'mecab-wordpiece'
  cache_dir: ../../../../../src/tokenizer/
