name: HAN

args:
  _target_: src.model.HAN.HierAttnNet
  vocab_size: 32000
  weight_drop: 0.0
  locked_drop: 0.0
  embed_drop: 0.0
  last_drop: 0.0
  word_hidden_dim: 100
  sent_hidden_dim: 100
  padding_idx: 1
  num_class: 2

data_module:
  _target_: src.datamodule.HANDataModule.CreateHANDataModule
  batch_size: 64