name: hf_hierdeberta

args:
  _target_: src.model.hierarchical.HierDeBERTa.HierDeBERTa
  wordattennet_params:
    pretrained_model_name_or_path: 'ku-nlp/deberta-v2-base-japanese'
    additional_special_tokens: ['<person>']
    personal_pronouns: ['君', 'きみ', 'あなた' ,'彼', '彼女']
    dropout: 0.1

  sentattennet_params:
    hidden_dim: 768
  
  dropout: 0.1
  num_class: 2

data_module:
  _target_: src.datamodule.HFModelDataModule.CreateHFModelDataModule
  batch_size: 64
