name: HierRoBERTaGRU

args:
  _target_: src.model.HierRoBERTaGRU.HierchicalRoBERTaGRU
  num_labels: 2
  output_attentions: True
  sent_embed_dim: 50
  doc_embed_dim: 50
  pooling_strategy: max
  update_last_layer: True
  weight_drop: 0.0
  classifier_drop_out: 0.0

data_module:
  _target_: src.datamodule.HFModelDataModule.CreateHFModelDataModule
  batch_size: 64
