name: FusedAdam

args:
  _target_: deepspeed.ops.adam.FusedAdam
  lr: 1e-3
  # betas: (0.9, 0.999)
  # eps: 1e-8
  weight_decay: 1e-2
  # amsgrad: False
  # bias_correction: True
  adam_w_mode: True
  amsgrad: False
  set_grad_none: True