name: bert_v3

args:
  _target_: src.tokenizer.HFTokenizer.HFTokenizer
  pretrained_model_name_or_path: cl-tohoku/bert-base-japanese-v3
  additional_special_tokens: ['<person>']
  max_length: 256
  doc_length: 20
