name: hf_deberta

args:
  _target_: src.tokenizer.HFTokenizer.HFTokenizer
  pretrained_model_name_or_path: ku-nlp/deberta-v2-base-japanese
  additional_special_tokens: ['<person>']
  max_length: 4096
